pipeline {
    agent any
    tools {
        terraform 'terraform v1.3.4'
    }

    stages {
        stage('Git Iac Checkout') {
            steps {
                git 'https://github.com/rafiuddinsadik/iac_assignment.git'
            }
        }
        stage('Terraform Run') {
            steps {
                sh 'terraform init'
                sh 'terraform plan'
//                 sh 'terraform apply --auto-approve'
            }
        }
    }
}
